import { TaskProvider } from '@/context/TaskContext';
import './globals.css';
import Navbar from '@/components/Navbar';
import { Toaster } from './Toaster';

export const metadata = {
	title: 'Tasks App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Navbar />
				<TaskProvider>
					{children}
					<Toaster />
				</TaskProvider>
			</body>
		</html>
	);
}
